/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SlyDog123123 (https://sketchfab.com/SlyDog123123)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robert-the-robot-bb4f731ba31d43ea814ed5db871e1c23
Title: Robert the Robot
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Robo(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/robo/scene.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    console.log(actions);
    actions["Take 01"].play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -Math.PI]}>
          <group name="Root">
            <group
              name="Sun"
              position={[-38.305, 48.966, 63.647]}
              rotation={[-0.701, -0.587, -0.597]}>
              <group name="Sun_1" />
            </group>
            <group
              name="Sun002"
              position={[54.31, 45.032, 42.989]}
              rotation={[-1.055, 0.722, -1.779]}>
              <group name="Sun002_1" />
            </group>
            <group
              name="Sun001"
              position={[5.277, -65.613, 58.931]}
              rotation={[1.121, -0.049, 1.677]}>
              <group name="Sun001_1" />
            </group>
            <group name="Sphere003" position={[0.1, -0.073, 25.1]}>
              <mesh
                name="Sphere003_0"
                castShadow
                receiveShadow
                geometry={nodes.Sphere003_0.geometry}
                material={materials.InvisiScreen}
              />
            </group>
            <group
              name="Screen2"
              position={[0.1, -0.073, 12.063]}
              rotation={[0, 0, 2.239]}
              scale={[11.138, 11.138, 8.51]}>
              <mesh
                name="Screen2_0"
                castShadow
                receiveShadow
                geometry={nodes.Screen2_0.geometry}
                material={materials.InvisiScreen}
              />
            </group>
            {/* <group name="Cube006" position={[-15.034, -15.626, 3.341]} scale={3.2}>
              <mesh
                name="Cube006_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube006_0.geometry}
                material={materials.material}
              />
            </group> */}
            {/* <group
              name="Cube005"
              position={[-12.864, 15.629, 3.104]}
              rotation={[0, 0, 0.295]}
              scale={2.963}>
              <mesh
                name="Cube005_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube005_0.geometry}
                material={materials.material}
              />
            </group> */}
            {/* <group
              name="Cube004"
              position={[15.877, -5.146, 2.963]}
              rotation={[2.906, 0.7, 0.356]}
              scale={[-2.471, 2.471, 1.573]}>
              <mesh
                name="Cube004_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube004_0.geometry}
                material={materials.material}
              />
            </group> */}
            {/* <group
              name="Cube003"
              position={[20.44, -7.963, 1.714]}
              rotation={[Math.PI, 0, 0.27]}
              scale={[-2.471, 4.885, 1.573]}>
              <mesh
                name="Cube003_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube003_0.geometry}
                material={materials.material}
              />
            </group> */}
            {/* <group name="Cube002" position={[-9.218, -15.867, 2.061]} scale={1.92}>
              <mesh
                name="Cube002_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube002_0.geometry}
                material={materials.material}
              />
            </group> */}
            {/* <group name="Cube001" position={[-15.873, -9.746, 2.061]} scale={1.92}>
              <mesh
                name="Cube001_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube001_0.geometry}
                material={materials.material}
              />
            </group> */}
            {/* <group name="Circle" position={[0, 0, 0.141]}>
              <mesh
                name="Circle_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle_0.geometry}
                material={materials.Ground}
              />
            </group> */}
            <group name="Armature001" position={[0, 0.785, 18.512]}>
              <primitive object={nodes.Armature001_rootJoint} />
              <skinnedMesh
                name="Robot_0"
                geometry={nodes.Robot_0.geometry}
                material={materials.Robot}
                skeleton={nodes.Robot_0.skeleton}
              />
              <skinnedMesh
                name="Robot_1"
                geometry={nodes.Robot_1.geometry}
                material={materials.Screen}
                skeleton={nodes.Robot_1.skeleton}
              />
              <skinnedMesh
                name="Robot_2"
                geometry={nodes.Robot_2.geometry}
                material={materials.Face}
                skeleton={nodes.Robot_2.skeleton}
              />
              <group
                name="Robot"
                position={[0, 0.055, -0.07]}
                rotation={[0, 0, -0.391]}
                scale={4.506}
              />
            </group>
            <group name="Circle001" position={[0, -0.158, 22.844]} scale={[18.14, 18.14, 14.793]}>
              <mesh
                name="Circle001_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle001_0.geometry}
                material={materials.InvisiScreen}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/robo/scene.gltf')
